# Generated by Django 4.0.4 on 2023-01-25 23:12

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('ci', models.CharField(choices=[('V', 'V'), ('E', 'E')], max_length=1, null=True)),
                ('num_ci', models.CharField(max_length=8, null=True, validators=[django.core.validators.RegexValidator('^[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+$')])),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, null=True)),
                ('hora_de_entrada', models.DateField(blank=True, null=True)),
                ('hora_de_salida', models.DateField(blank=True, null=True)),
                ('docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asistencia.docente')),
            ],
        ),
    ]
