# Generated by Django 4.1.4 on 2023-01-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='hora_de_entrada',
            new_name='entrada',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='hora_de_salida',
            new_name='salida',
        ),
    ]
