# Generated by Django 4.1.4 on 2023-01-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_rename_hora_de_entrada_registro_entrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='docente',
            name='uc',
            field=models.ManyToManyField(to='asistencia.uc', verbose_name='Unidades Curriculares'),
        ),
    ]
