# Generated by Django 4.1.4 on 2023-01-26 15:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_uc_docente_uc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, null=True)),
                ('entrada', models.DateField(blank=True, null=True)),
                ('salida', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='uc',
            options={'verbose_name': 'Unidad Curricular', 'verbose_name_plural': 'Unidades Curriculares'},
        ),
        migrations.RemoveField(
            model_name='docente',
            name='uc',
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
        migrations.AddField(
            model_name='horario',
            name='docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asistencia.docente'),
        ),
        migrations.AddField(
            model_name='horario',
            name='uc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='asistencia.uc'),
        ),
    ]
