# Generated by Django 4.1.4 on 2023-01-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_horario_alter_uc_options_remove_docente_uc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='fecha',
        ),
        migrations.AddField(
            model_name='horario',
            name='dia',
            field=models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=10, null=True),
        ),
    ]
